import { Literata, Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { ModalProvider } from "@/context/ModalContext";

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  display: "swap",
});

const workSans = Work_Sans({
  variable: "--font-workSans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${literata.variable} ${workSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ModalProvider>
          <Header />
          <main className="flex flex-1">{children}</main>
          <Footer />
        </ModalProvider>
        <Toaster position="top-right" richColors closeButton />
        {/* Dedicated portal root for modals — keeps modal DOM outside the app tree */}
        <div id="modal-root" />
      </body>
    </html>
  );
}
